### ISSUE TITLE
List item inside div (html semantics)

### ISSUE THREAD

**Issue by timneutkens** [toonvd/magento-localstorage-recentlyviewed#14]
As show in the screenshot. Moving dom generation to javascript to fix the security issue of #12 
this ticket is just for my reference
<img width="782" alt="screen shot 2016-04-16 at 00 02 56" src="https://cloud.githubusercontent.com/assets/6324199/14576093/9d10fd80-0366-11e6-828a-cd173ac5e441.png">

**Comment by toonvd** [comment]
@timneutkens is there no other way to solve the security issue, dom generation is something to be avoided if possible when looking at performance / best practise. This is why I used the placeholders. Sanitizing the output would be a cleaner option.

**Comment by toonvd** [comment]
I will leave this open, for now, this suffices.

**Comment by timneutkens** [comment]
Closing this, working through my issues list 😉
